- name: Copy nginx config
  copy:
    dest: /etc/nginx/nginx.conf
    src: roles/common/templates/nginx-conf-OK.j2
    owner: aniss
    group: aniss
    mode: '0644'

- name: install nginx
  hosts: localhost
  become: true
  roles:
    - role: nginxinc.nginx

- name: reload params nginx
  command: nginx -s reload